name: Deploy to GitHub Pages

on:
  # Trigger the deployment workflow when the 'workflow_run' event occurs
  workflow_run:
    workflows: ["Generate Test Result and Update HTML"] # Name of the test result update workflow
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Add a condition to check the output variable from the previous workflow
      - name: Deploy if Test Result Updated
        if: success() && env.test_result_updated == 'true'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: main
          folder: .
